Add scons script for tfm package
RT-Thread-packages/trusted-firmware-m pull request #2
Opened 2020-02-15 09:24 UTC by karl-zh

Add scons script for tfm package

The Scons script will add all necessary files and folder to project.

2020-02-15 09:26 UTC, armink commented on SConscript
> +CPPDEFINES = ['RT_USING_TFM']
.c 中的 `#infdef RT_USING_TFM` 是不是改为 `#ifdef PKG_USING_TFM` 也行？

2020-02-15 11:31 UTC, karl-zh commented on SConscript
> +CPPDEFINES = ['RT_USING_TFM']
> .c 中的 `#infdef RT_USING_TFM` 是不是改为 `#ifdef PKG_USING_TFM` 也行？

Updated:
https://github.com/RT-Thread/rt-thread/pull/3372/commits/95f4c7d3745dc3db04922d9a260ef2e6357a273c

2020-02-15 12:37 UTC, armink requested changes

2020-02-15 12:37 UTC, armink commented on SConscript
> +print(src)
这个打印日志去掉吧

2020-02-15 12:47 UTC, karl-zh commented on SConscript
> +print(src)
> 这个打印日志去掉吧

Removed

2020-02-15 12:49 UTC, armink commented
重复了，这个关掉？

2020-02-15 12:51 UTC, karl-zh commented
> 重复了，这个关掉？

No.
Different branches for different PR.

2020-02-15 13:02 UTC, armink commented
OK，到时候是不是重新 release 一下

2020-02-15 14:18 UTC, merged

2020-02-17 01:23 UTC, karl-zh commented
> OK，到时候是不是重新 release 一下

应该是，有了link后更新package里头的json再。谢谢

2020-02-17 01:40 UTC, armink commented
可以把之前的 release 删了，重新发布，就是你本地的缓存得清理一下

2020-02-17 01:42 UTC, karl-zh commented
> 可以把之前的 release 删了，重新发布，就是你本地的缓存得清理一下

可以，面更新连接了，发布好了告知我删local。

2020-02-17 01:48 UTC, armink commented
搞好了。如果开启的镜像，可能得等等同步机器人